### ISSUE TITLE
Have not reported missing closing bracket

### ISSUE THREAD

**Issue by pkuczynski** [messageformat/parser#10]
Example:

`const message = '{count, plural, one {car} other {cars}'`

Expected output:

`SyntaxError: Expected "}" not found.`

Actual output:

```js
[ { type: 'function',
    arg: 'count',
    key: 'plural',
    param: ' one {car' },
  ' other ',
  { type: 'argument', arg: 'cars' } ]
```

**Comment by eemeli** [comment]
This appears to already be fixed in the master branch, which clearly should be packaged into a new release.

**Comment by eemeli** [comment]
Fixed in v4.

**Comment by pkuczynski** [comment]
Thanks! :)
