### ISSUE TITLE
Definition of ID

### ISSUE THREAD

**Issue by nkovacs** [messageformat/parser#5]
The definition of id requires the first character to be ASCII alphanumeric or $ or _, but then allows almost any character (except ` \t\n\r,.+={}`). This is not consistent with ICU, which allows anything that's not [Pattern_Syntax](http://unicode.org/cldr/utility/list-unicodeset.jsp?a=%5B:Pattern_Syntax:%5D&abb=on&g=) or [Pattern_White_Space](http://unicode.org/cldr/utility/list-unicodeset.jsp?a=%5B%3APattern_White_Space%3A%5D&abb=on&g=&i=), and it's also not internally consistent, e.g. there's a testcase that says "shouldn't allow characters in variables that aren't valid JavaScript identifiers", and it  tests `{☺}`, but `{a☺}` would be allowed.

**Comment by SlexAxton** [comment]
I think the actual specs didn't exist (or I couldn't find them) when I first wrote the parser. And I think a lot of those choices have just followed us since then. I was mostly just trying to reverse engineer the api via the c++ and java docs.

That said, I'm happy to see any of this getting updated to be in line with the real life spec, all with a major version bump.

**Comment by nkovacs** [comment]
I'm not sure what to do about whitespace. The definition of `\s` in javascript is different, it doesn't contain \u0085, but it contains a few more unicode characters.

Pattern_White_Space is `[\u0009-\u000d \u0085\u200e\u200f\u2028\u2029]`, `\s` is `[ \f\n\r\t\v\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]`

I just did a test in php, and `\u3000` is accepted as a variable there (it uses the C port of ICU).

**Comment by SlexAxton** [comment]
If it's not spec'd, I think if we just pick a set and doc it, it's fine. I'm not terribly concerned about all the edgecase whitespace characters, to be totally honest. Happy to trust your opinion, with slight preference to interop with other langs if you need a tie-breaker.

**Comment by nkovacs** [comment]
Interop it is then. I wrote a php script that checks all the unicode characters as variable names and exports the results to a json, then I tested it with the parser to make sure the results are the same: https://github.com/nkovacs/icu-messageformat-parser/commit/ed7688d36e490ecfc46e1fd2b79095632a264cd2
